name: Publish package to GitHub Packages
on:
  push:
    branches:
      - aws-socket-timeout-publish
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Publish package
        run: mvn -DskipTests=true deploy -pl :spring-ai-bedrock-converse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
